# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/message.proto\"_\n\x13LocalSamplesRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x14num_positive_samples\x18\x02 \x01(\x03\x12\x1c\n\x14num_negative_samples\x18\x03 \x01(\x03\"(\n\rReceivedReply\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"$\n\x14GlobalSamplesRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"i\n\x12GlobalSamplesReply\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x1c\n\x14num_positive_samples\x18\x02 \x01(\x03\x12\x1c\n\x14num_negative_samples\x18\x03 \x01(\x03\"S\n\x12SendSamplesRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c*,\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x32\x99\x01\n\x17UploadNumSamplesService\x12<\n\x14upload_local_samples\x12\x14.LocalSamplesRequest\x1a\x0e.ReceivedReply\x12@\n\x12get_global_samples\x12\x15.GlobalSamplesRequest\x1a\x13.GlobalSamplesReply2O\n\x14UploadSamplesService\x12\x37\n\x0eupload_samples\x12\x13.SendSamplesRequest\x1a\x0e.ReceivedReply(\x01\x62\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
SUCCESS = 0
PENDING = 1
FAIL = 2


_LOCALSAMPLESREQUEST = DESCRIPTOR.message_types_by_name['LocalSamplesRequest']
_RECEIVEDREPLY = DESCRIPTOR.message_types_by_name['ReceivedReply']
_GLOBALSAMPLESREQUEST = DESCRIPTOR.message_types_by_name['GlobalSamplesRequest']
_GLOBALSAMPLESREPLY = DESCRIPTOR.message_types_by_name['GlobalSamplesReply']
_SENDSAMPLESREQUEST = DESCRIPTOR.message_types_by_name['SendSamplesRequest']
LocalSamplesRequest = _reflection.GeneratedProtocolMessageType('LocalSamplesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSAMPLESREQUEST,
  '__module__' : 'protos.message_pb2'
  # @@protoc_insertion_point(class_scope:LocalSamplesRequest)
  })
_sym_db.RegisterMessage(LocalSamplesRequest)

ReceivedReply = _reflection.GeneratedProtocolMessageType('ReceivedReply', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEDREPLY,
  '__module__' : 'protos.message_pb2'
  # @@protoc_insertion_point(class_scope:ReceivedReply)
  })
_sym_db.RegisterMessage(ReceivedReply)

GlobalSamplesRequest = _reflection.GeneratedProtocolMessageType('GlobalSamplesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSAMPLESREQUEST,
  '__module__' : 'protos.message_pb2'
  # @@protoc_insertion_point(class_scope:GlobalSamplesRequest)
  })
_sym_db.RegisterMessage(GlobalSamplesRequest)

GlobalSamplesReply = _reflection.GeneratedProtocolMessageType('GlobalSamplesReply', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSAMPLESREPLY,
  '__module__' : 'protos.message_pb2'
  # @@protoc_insertion_point(class_scope:GlobalSamplesReply)
  })
_sym_db.RegisterMessage(GlobalSamplesReply)

SendSamplesRequest = _reflection.GeneratedProtocolMessageType('SendSamplesRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDSAMPLESREQUEST,
  '__module__' : 'protos.message_pb2'
  # @@protoc_insertion_point(class_scope:SendSamplesRequest)
  })
_sym_db.RegisterMessage(SendSamplesRequest)

_UPLOADNUMSAMPLESSERVICE = DESCRIPTOR.services_by_name['UploadNumSamplesService']
_UPLOADSAMPLESSERVICE = DESCRIPTOR.services_by_name['UploadSamplesService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=393
  _STATUS._serialized_end=437
  _LOCALSAMPLESREQUEST._serialized_start=24
  _LOCALSAMPLESREQUEST._serialized_end=119
  _RECEIVEDREPLY._serialized_start=121
  _RECEIVEDREPLY._serialized_end=161
  _GLOBALSAMPLESREQUEST._serialized_start=163
  _GLOBALSAMPLESREQUEST._serialized_end=199
  _GLOBALSAMPLESREPLY._serialized_start=201
  _GLOBALSAMPLESREPLY._serialized_end=306
  _SENDSAMPLESREQUEST._serialized_start=308
  _SENDSAMPLESREQUEST._serialized_end=391
  _UPLOADNUMSAMPLESSERVICE._serialized_start=440
  _UPLOADNUMSAMPLESSERVICE._serialized_end=593
  _UPLOADSAMPLESSERVICE._serialized_start=595
  _UPLOADSAMPLESSERVICE._serialized_end=674
# @@protoc_insertion_point(module_scope)
