# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"4\n\x08Response\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x15\n\rresponse_data\x18\x02 \x01(\x05\"@\n\tFileChunk\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\r\n\x05\x63hunk\x18\x03 \x01(\x0c\x32\x46\n\x08GRPCDemo\x12:\n\x15\x43lientStreamingMethod\x12\x0f.demo.FileChunk\x1a\x0e.demo.Response(\x01\x62\x06proto3')



_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_FILECHUNK = DESCRIPTOR.message_types_by_name['FileChunk']
Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Response)
  })
_sym_db.RegisterMessage(Response)

FileChunk = _reflection.GeneratedProtocolMessageType('FileChunk', (_message.Message,), {
  'DESCRIPTOR' : _FILECHUNK,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.FileChunk)
  })
_sym_db.RegisterMessage(FileChunk)

_GRPCDEMO = DESCRIPTOR.services_by_name['GRPCDemo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=20
  _RESPONSE._serialized_end=72
  _FILECHUNK._serialized_start=74
  _FILECHUNK._serialized_end=138
  _GRPCDEMO._serialized_start=140
  _GRPCDEMO._serialized_end=210
# @@protoc_insertion_point(module_scope)
